### ISSUE TITLE
Emit an empty array []

### ISSUE THREAD

**Issue by ckonstanski** [hankhero/cl-json#17]
Sadly I am working with a REST API that requires the presence of parameters in the JSON even if the value is an empty array []. I am struggling to find a way to get cl-json to emit one of these. '() results in null, '(nil) resuls in [null], etc. Is there a trick for this?

**Comment by ckonstanski** [comment]
If I change cl-json::_json-array-type_ to something other than LIST, and the new json-arra-type can handle being empty without being confused for nil, is that a valid workaround? Gonna try it though it's going to open a mega can of worms.

**Comment by ckonstanski** [comment]
I found that simply using an empty vector #() causes cl-json to emit an empty array []. If I'm not imagining things, I think I am good to go.

**Comment by ckonstanski** [comment]
Verified. Closing.

**Comment by paulvaneecke** [comment]
Thanks, I was struggling with the same problem!
