### ISSUE TITLE
Connection broken by remote peer when open large file

### ISSUE THREAD

**Issue by not-null-nil** [hankhero/cl-json#34]
When using emacs+slime:
```
(cl-json:decode-json-from-source (pathname "/path/to/test.json"))
```
will give 
```
Connection broken by remote peer when open large file
```
when open large file(14M)
[file link](https://drive.google.com/file/d/1zX2kUGMN-bEI2hsbgwlEoLy0qUbBWQEM/view?usp=sharing)
while in sbcl(terminal) it is ok.

**Comment by rpgoldman** [comment]
This really is a SLIME issue, and not an issue with CL-json

--  
Robert P. Goldman

**Comment by not-null-nil** [comment]
Okay, then I think this could just be close.
